"""Add is_deleted to Message

Revision ID: 125b2f71465c
Revises: 8f7462d980d0
Create Date: 2025-06-04 09:09:38.177726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125b2f71465c'
down_revision = '8f7462d980d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
