"""added two more tables

Revision ID: 28b59fd93c05
Revises: 965b86f42144
Create Date: 2025-05-05 06:08:40.954561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b59fd93c05'
down_revision = '965b86f42144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['adoption_application.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adoption_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('answers', sa.Text(), nullable=True))
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.TEXT(), nullable=True))
        batch_op.drop_column('answers')
        batch_op.drop_column('application_date')

    op.drop_table('message')
    # ### end Alembic commands ###
