"""deleted location and added city to Pet table

Revision ID: 965b86f42144
Revises: afb098b7798f
Create Date: 2025-05-02 08:17:57.101556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965b86f42144'
down_revision = 'afb098b7798f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('city')

    # ### end Alembic commands ###
