"""added adoption_date column to Pet table

Revision ID: af8088139a99
Revises: 28b59fd93c05
Create Date: 2025-05-25 07:36:01.977449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8088139a99'
down_revision = '28b59fd93c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adoption_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('adoption_date')

    # ### end Alembic commands ###
